<?php
/**
 * Created by PhpStorm.
 * User: aiwes
 * Date: 2020/4/25
 * Time: 11:21
 */

namespace app\mobile\validate;

use think\Validate;

class ChildRoll extends Validate
{
    protected $rule = [
        //  学生个人基础信息
        'id' => 'require|number',
        'child_id' => 'require|number',
        'region_id' => 'require|number',
        'school_id' => 'require|number',
        'real_name' => 'require|chsAlpha|length:2,24',
        'sex' => 'require|in:1,2,3',
        'birthday' => 'require|integer|length:8',
        'birthplace' => 'require|integer|length:6',
        'nativeplace' => 'require|length:2,255',
        'nation' => 'require|chsAlpha|length:1,24',
        'nationality' => 'require|length:1,24',
        'card_type' => 'require|in:1,2,3',
        'id_card' => 'require',
        'overseas' => 'require|in:0,1',
        'politics' => 'length:1,10',
        'health' => 'require|length:1,10',
        'photo' => 'require',
        //  学生个人辅助信息
        'school_roll_id' => 'require|number',
        'name_pinyin' => 'alpha|length:2,20',
        'name_used' => 'chsAlpha|length:1,20',
        'id_card_validity' => 'length:1,24',
        'residence' => 'require|integer|length:6',
        'birthplace_attr' => 'require|length:1,20',
        'specialty' => 'length:1,255',
        //学生学籍基本信息
        'student_code_auxiliary' => 'length:1,50',
        'student_number' => 'length:1,50',
        'grade_code' => 'require|length:1,20',
        'class_code' => 'require|length:1,20',
        'entrance_time' => 'require|length:6',
        'entrance_type' => 'require|length:1,20',
        'study_method' => 'require|length:1,20',
        'student_source' => 'length:1,20',
        //学生个人联系信息
        'current_address' => 'require|length:1,50',
        'mailing_address' => 'require|length:1,50',
        'home_address' => 'require|length:1,50',
        'mobile' => 'require|mobile',
        'postal_code' => 'require|zip',
        'email' => 'email',
        'homepage' => 'length:1,50',
        //学生个人扩展信息
        'onlyed' => 'require|in:0,1',
        'preschooled' => 'require|in:0,1',
        'stayed' => 'require|in:0,1',
        'flowed' => 'require|in:0,1',
        'orphaned' => 'require|in:0,1',
        'martyred' => 'require|in:0,1',
        'regular_class' => 'length:1,20',
        'disability_type' => 'length:1,20',
        'purchased' => 'in:0,1',
        'supported' => 'require|in:0,1',
        'subsidy' => 'require|in:0,1',
        //上下学交通方式
        'distance' => 'float',
        'transportation' => 'length:1,20',
        'school_bused' => 'in:0,1',
        //家庭成员或监护人一
        'one_real_name' => 'require|chsAlpha|length:2,20',
        'one_relation' => 'require|chsAlpha|length:1,20',
        'one_relation_remark' => 'length:1,20',
        'one_nation' => 'length:1,20',
        'one_work_address' => 'length:1,20',
        'one_current_address' => 'require|length:1,50',
        'one_residence' => 'require|integer|length:6',
        'one_mobile' => 'require|mobile',
        'one_guardian' => 'require|in:0,1',
        'one_card_type' => 'in:1,2,3',
        'one_id_card' => 'idCard',
        'one_duties' => 'length:1,18',
        //家庭成员或监护人二
        'two_real_name' => 'require|chsAlpha|length:2,20',
        'two_relation' => 'require|chsAlpha|length:1,20',
        'two_relation_remark' => 'length:1,20',
        'two_nation' => 'chsAlpha|length:1,20',
        'two_work_address' => 'length:1,20',
        'two_current_address' => 'require|length:1,50',
        'two_residence' => 'require|integer|length:6',
        'two_mobile' => 'require|mobile',
        'two_guardian' => 'require|in:0,1',
        'two_card_type' => 'in:1,2,3',
        'two_id_card' => 'idCard',
        'two_duties' => 'length:1,18',

        'student_code' => 'length:1,24|unique:sys_school_roll,deleted=0',
        'graduation_school' => 'require|length:2,50',
        'graduation_school_code' => 'require|length:2,50',
        'identification' => 'length:1,50',
        'deleted' => 'in:0,1',
    ];

    protected $message = [
        //  学生个人基础信息
        'id.require' => '请选择需要操作的信息',
        'id.number' => '非法操作',
        'child_id.require' => '学生不能为空',
        'child_id.number' => '非法操作',
        'region_id.require' => '区域不能为空',
        'region_id.number' => '非法操作',
        'school_id.require' => '学校不能为空',
        'school_id.number' => '非法操作',
        'real_name.require' => '请填写真实姓名',
        'real_name.chsAlpha' => '真实姓名格式不正确',
        'real_name.length' => '真实姓名长度不正确',
        'sex.require' => '请选择性别',
        'sex.in' => '非法操作',
        'birthday.require' => '请填写出生日期',
        'birthday.integer' => '出生日期格式不正确',
        'birthday.length' => '出生日期长度不正确',
        'birthplace.require' => '请填写出生地',
        'birthplace.integer' => '出生地格式不正确',
        'birthplace.length' => '出生地长度不正确',
        'nativeplace.require' => '请填写籍贯',
        'nativeplace.length' => '籍贯长度不正确',
        'nation.require' => '请填写民族',
        'nation.chsAlpha' => '民族格式不正确',
        'nation.length' => '民族长度不正确',
        'nationality.require' => '请填写国籍/地区',
        'nationality.length' => '国籍/地区长度不正确',
        'card_type.require' => '请选择证件类型',
        'card_type.in' => '非法操作',
        'id_card.require' => '请填写身份证号',
        'overseas.require' => '请选择是否港澳台侨外',
        'overseas.in' => '非法操作',
        'politics.length' => '政治面貌长度不正确',
        'health.require' => '请填写健康状态',
        'health.length' => '健康状态长度不正确',
        'photo.require' => '请上传本人照片',
        //  学生个人辅助信息
        'school_roll_id.require' => '请选择需要操作的信息',
        'school_roll_id.number' => '非法操作',
        'name_pinyin.alpha' => '姓名拼音格式不正确',
        'name_pinyin.length' => '姓名拼音长度不正确',
        'name_used.chsAlpha' => '曾用名格式不正确',
        'name_used.length' => '曾用名长度不正确',
        'id_card_validity.length' => '身份证有效期长度不正确',
        'residence.require' => '请填写户口所在（区域代码）',
        'residence.integer' => '户口所在（区域代码）地格式不正确',
        'residence.length' => '户口所在（区域代码）长度不正确',
        'birthplace_attr.require' => '请选择户口性质',
        'birthplace_attr.length' => '户口性质长度不正确',
        'specialty.length' => '特长长度不正确',
        //学生学籍基本信息
        'student_code_auxiliary.length' => '学籍辅号长度不正确',
        'student_number.length' => '班内学号长度不正确',
        'grade_code.require' => '请填写年级',
        'grade_code.length' => '年级长度不正确',
        'class_code.require' => '请填写班级号',
        'class_code.length' => '班级号长度不正确',
        'entrance_time.require' => '请填写入学时间',
        'entrance_time.length' => '入学时间长度不正确',
        'entrance_type.require' => '请填写入学方式',
        'entrance_type.length' => '入学方式长度不正确',
        'study_method.require' => '请填写就读方式',
        'study_method.length' => '就读方式长度不正确',
        'student_source.length' => '学生来源长度不正确',
        //学生个人联系信息
        'current_address.require' => '请填写现住址',
        'current_address.length' => '现住址长度不正确',
        'mailing_address.require' => '请填写通信地址',
        'mailing_address.length' => '通信地址长度不正确',
        'home_address.require' => '请填写家庭地址',
        'home_address.length' => '家庭地址长度不正确',
        'mobile.require' => '请填写手机号码',
        'mobile.mobile' => '手机号码格式错误',
        'postal_code.require' => '请填写邮政编码',
        'postal_code.zip' => '邮政编码格式错误',
        'email.email' => '电子邮箱格式错误',
        'homepage.length' => '主页地址长度不正确',
        //学生个人扩展信息
        'onlyed.require' => '请选择是否独生子女',
        'onlyed.in' => '非法操作',
        'preschooled.require' => '请选择是否受过学前教育',
        'preschooled.in' => '非法操作',
        'stayed.require' => '请选择是否留守儿童',
        'stayed.in' => '非法操作',
        'flowed.require' => '请选择是否进城务工人员随迁子女',
        'flowed.in' => '非法操作',
        'orphaned.require' => '请选择是否孤儿',
        'orphaned.in' => '非法操作',
        'martyred.require' => '请选择是否烈士或优抚子女',
        'martyred.in' => '非法操作',
        'regular_class.length' => '随班就读长度不正确',
        'disability_type.length' => '残疾类型长度不正确',
        'purchased.in' => '非法操作',
        'supported.require' => '请选择是否需要申请资助',
        'supported.in' => '非法操作',
        'subsidy.require' => '请选择是否享受一补',
        'subsidy.in' => '非法操作',
        //学生上下学交通方式
        'distance.float' => '距离格式错误',
        'transportation.length' => '上下学交通方式长度不正确',
        'school_bused.in' => '非法操作',
        //家庭成员或监护人一
        'one_real_name.require' => '请填写家庭成员姓名',
        'one_real_name.chsAlpha' => '家庭成员姓名格式不正确',
        'one_real_name.length' => '家庭成员姓名长度不正确',
        'one_relation.require' => '请填写关系说明',
        'one_relation.chsAlpha' => '关系说明格式不正确',
        'one_relation.length' => '关系说明长度不正确',
        'one_relation_remark.length' => '关系说明长度不正确',
        'one_nation.length' => '民族长度不正确',
        'one_work_address.length' => '工作单位长度不正确',
        'one_current_address.require' => '请填写现住址',
        'one_current_address.length' => '现住址长度不正确',
        'one_residence.require' => '请填写户口所在（区域代码）',
        'one_residence.integer' => '户口所在（区域代码）地格式不正确',
        'one_residence.length' => '户口所在（区域代码）长度不正确',
        'one_mobile.require' => '请填写联系电话',
        'one_mobile.mobile' => '联系电话格式错误',
        'one_guardian.require' => '请选择是否监护人',
        'one_guardian.in' => '非法操作',
        'one_card_type.in' => '非法操作',
        'one_id_card.idCard' => '身份证件号格式不正确',
        'one_duties.length' => '职务长度不正确',
        //二
        'two_real_name.require' => '请填写家庭成员姓名',
        'two_real_name.chsAlpha' => '家庭成员姓名格式不正确',
        'two_real_name.length' => '家庭成员姓名长度不正确',
        'two_relation.require' => '请填写关系说明',
        'two_relation.chsAlpha' => '关系说明格式不正确',
        'two_relation.length' => '关系说明长度不正确',
        'two_relation_remark.length' => '关系说明长度不正确',
        'two_nation.length' => '民族长度不正确',
        'two_work_address.length' => '工作单位长度不正确',
        'two_current_address.require' => '请填写现住址',
        'two_current_address.length' => '现住址长度不正确',
        'two_residence.require' => '请填写户口所在（区域代码）',
        'two_residence.integer' => '户口所在（区域代码）地格式不正确',
        'two_residence.length' => '户口所在（区域代码）长度不正确',
        'two_mobile.require' => '请填写联系电话',
        'two_mobile.mobile' => '联系电话格式不正确',
        'two_guardian.in' => '非法操作',
        'two_card_type.in' => '非法操作',
        'two_id_card.idCard' => '身份证件号格式不正确',
        'two_duties.length' => '职务长度不正确',

        'student_code.length' => '学籍号长度不正确',
        'student_code.unique' => '学籍号不能重复',
        'graduation_school.length' => '毕业学校长度不正确',
        'graduation_school.require' => '毕业学校不能为空',
        'graduation_school_code.length' => '毕业学校编码长度不正确',
        'graduation_school_code.require' => '毕业学校编码不能为空',
        'identification.length' => '学籍接续标识长度不正确',
        'deleted.in' => '非法操作',

    ];

    protected $scene = [
        'info' => [
            'id'
        ],
        'addbasics' =>[
            'real_name',
            'sex',
            'birthday',
            'nativeplace',
            'nation',
            'nationality',
            'card_type',
            'id_card',
            'overseas',
            'politics',
            'health',
        ],

        'addside' =>[
            'school_roll_id',
            'name_pinyin',
            'name_used',
            'id_card_validity',
            'residence',
            'birthplace_attr',
            'specialty',
        ],
        'addroll' =>[
            'school_roll_id',
            'student_code_auxiliary',
            'student_number',
            'grade_code',
            'class_code',
            'entrance_time',
            'entrance_type',
            'study_method',
            'student_source',
        ],
        'addcontact' =>[
            'school_roll_id',
            'current_address',
            'mailing_address',
            'home_address',
            'mobile',
            'postal_code',
            'email',
            'homepage',
        ],
        'addextent' =>[
            'school_roll_id',
            'onlyed',
            'preschooled',
            'stayed',
            'flowed',
            'orphaned',
            'martyred',
            'regular_class',
            'disability_type',
            'purchased',
            'supported',
            'subsidy',
        ],
        'addtraffic' =>[
            'school_roll_id',
            'distance',
            'transportation',
            'school_bused',
        ],
        'addfamilyone' =>[
            'school_roll_id',
            'one_real_name',
            'one_relation',
            'one_relation_remark',
            'one_nation',
            'one_work_address',
            'one_current_address',
            'one_residence',
            'one_mobile',
            'one_guardian',
            'one_card_type',
            'one_id_card',
            'one_duties',
        ],
        'addfamilytwo' =>[
            'school_roll_id',
            'two_real_name',
            'two_relation',
            'two_relation_remark',
            'two_nation',
            'two_work_address',
            'two_current_address',
            'two_residence',
            'two_mobile',
            'two_guardian',
            'two_card_type',
            'two_id_card',
            'two_duties',
        ],
        'addJuniorRoll' =>[
            'child_id',
            'real_name',
            'graduation_school',
            'graduation_school_code',
            'student_code',
        ]
    ];
}